vaadin.launch-browser=false
spring.application.name=lesnazrzutka
server.port=${PORT:8080}

# DataSource Configuration
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.h2.console.enabled=true

# Security Configuration
spring.security.user.name=admin
spring.security.user.password=admin

# Production
spring.profiles.active=production

